services:
  postgres:
    image: postgres:13.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: ../
    restart: always
    env_file:
      - ../.env
  
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
  
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.23.3-alpine
    container_name: procharity_nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ../.env


volumes:
  postgres_data: