services:
  postgres:
    image: postgres:13.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: ../
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ../.env
  
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
  
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: