services:
  postgres:
    image: postgres:13.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: ../
    restart: always
    env_file:
      - ../.env
  
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
  
    depends_on:
      postgres:
        condition: service_healthy

  swag:
    image: lscr.io/linuxserver/swag:2.4.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      - URL=some.url
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - EMAIL=some@email.com
    env_file:
      - ../.env
    volumes:
      - ../nginx_logs:/var/log/nginx
      - ./nginx/swag.conf:/config/nginx/site-confs/default.conf
      - keys:/config/keys
      - static:/var/html/static/:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend

volumes:
  keys:
  postgres_data: