"""empty message

Revision ID: ecf1ae095b51
Revises: fffdc2913bda
Create Date: 2023-07-20 09:31:46.272509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecf1ae095b51"
down_revision = "fffdc2913bda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("popularity", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "popularity")
    # ### end Alembic commands ###
